/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/allotment` | `/allotment`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/investors` | `/investors`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pan-cards` | `/pan-cards`; params?: Router.UnknownInputParams; } | { pathname: `/ipo/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/allotment` | `/allotment`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/investors` | `/investors`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pan-cards` | `/pan-cards`; params?: Router.UnknownOutputParams; } | { pathname: `/ipo/[slug]`, params: Router.UnknownOutputParams & { slug: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/allotment${`?${string}` | `#${string}` | ''}` | `/allotment${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/investors${`?${string}` | `#${string}` | ''}` | `/investors${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pan-cards${`?${string}` | `#${string}` | ''}` | `/pan-cards${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/allotment` | `/allotment`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/investors` | `/investors`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pan-cards` | `/pan-cards`; params?: Router.UnknownInputParams; } | `/ipo/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/ipo/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } };
    }
  }
}
